#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Jun 15 14:40:46 CEST 2025
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1749938934906
maven-metadata-maven-default-http-blocker.xml.error=Could not transfer metadata com.dabi.habitv\:framework/maven-metadata.xml from/to maven-default-http-blocker (http\://0.0.0.0/)\: Blocked mirror for repositories\: [dabi-repo (http\://dabiboo.free.fr/repository, default, releases+snapshots)]
maven-metadata-maven-default-http-blocker.xml/@default-maven-default-http-blocker-http\://0.0.0.0/.lastUpdated=1749991246205
maven-metadata-habitv-mirror.xml.lastUpdated=1749938934906
maven-metadata-dabi-repo.xml.lastUpdated=1749939311494
