#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Jun 15 11:28:44 CEST 2025
maven-metadata-habitv-mirror.xml.lastUpdated=1749979724218
maven-metadata-dabi-repo.xml.lastUpdated=1749979724218
