#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Jun 15 14:33:19 CEST 2025
maven-metadata-dabi-repo.xml.error=
maven-metadata-dabi-repo.xml.lastUpdated=1749990799747
maven-metadata-habitv-mirror.xml.error=
maven-metadata-habitv-mirror.xml.lastUpdated=1749990799746
