#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Jun 15 13:30:05 CEST 2025
maven-metadata-habitv-mirror.xml.lastUpdated=1749987005920
maven-metadata-dabi-repo.xml.lastUpdated=1749987005920
