#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Jun 15 11:28:45 CEST 2025
maven-metadata-maven-default-http-blocker.xml.error=Could not transfer metadata com.dabi.habitv\:core\:4.1.0-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http\://0.0.0.0/)\: Blocked mirror for repositories\: [dabi-repo (http\://dabiboo.free.fr/repository, default, releases+snapshots)]
maven-metadata-maven-default-http-blocker.xml/@default-maven-default-http-blocker-http\://0.0.0.0/.lastUpdated=1749979725187
maven-metadata-habitv-mirror.xml.lastUpdated=1749979725186
maven-metadata-dabi-repo.xml.lastUpdated=1749979725187
