#!/usr/bin/env python3
"""Generate plugins.txt, habitv-update-manifest.properties, and index.html."""

from __future__ import print_function

import os
import re
import sys


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

from validate_manifest_freshness import newest_jar_in_directory  # noqa: E402


def read_plugin_ids(plugins_pom):
    with open(plugins_pom, "r") as handle:
        content = handle.read()
    ids = re.findall(r"<module>([^<]+)</module>", content)
    return sorted(i for i in ids if i != "plugin-tester")


def latest_jar(version_dir):
    return newest_jar_in_directory(version_dir)


def build_manifest_lines(repository_root, plugin_ids):
    lines = [
        "# Generated by scripts/static-repo/generate_repository_metadata.py",
        "# type|groupId|artifactId|version|packaging|relativeUrl",
    ]
    group_root = os.path.join(repository_root, "com", "dabi", "habitv")
    for artifact_id in plugin_ids:
        artifact_dir = os.path.join(group_root, artifact_id)
        if not os.path.isdir(artifact_dir):
            print("warn: missing deployed plugin {}".format(artifact_id), file=sys.stderr)
            continue
        version_dirs = sorted(
            (name for name in os.listdir(artifact_dir) if os.path.isdir(os.path.join(artifact_dir, name))),
            reverse=True,
        )
        for version in version_dirs:
            version_dir = os.path.join(artifact_dir, version)
            jar_name = latest_jar(version_dir)
            if jar_name is None:
                continue
            relative = "com/dabi/habitv/{}/{}/{}".format(artifact_id, version, jar_name)
            lines.append(
                "plugin|com.dabi.habitv|{}|{}|jar|{}".format(artifact_id, version, relative)
            )
            break

    tools_root = os.path.join(repository_root, "tools")
    if os.path.isdir(tools_root):
        for tool_name in sorted(os.listdir(tools_root)):
            tool_dir = os.path.join(tools_root, tool_name)
            if not os.path.isdir(tool_dir):
                continue
            for version in sorted(os.listdir(tool_dir)):
                version_dir = os.path.join(tool_dir, version)
                if not os.path.isdir(version_dir):
                    continue
                zips = [name for name in os.listdir(version_dir) if name.endswith(".zip")]
                if not zips:
                    continue
                relative = "tools/{}/{}/{}".format(tool_name, version, zips[0])
                lines.append(
                    "tool|com.dabi.habitv|{}|{}|zip|{}".format(tool_name, version, relative)
                )
    return lines


def write_plugins_txt(repository_root, plugin_ids):
    path = os.path.join(repository_root, "plugins.txt")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("# Habitv plugin artifact ids (one per line, matches Maven artifactId)\n")
        for plugin_id in plugin_ids:
            handle.write(plugin_id + "\n")
    print("Wrote {} ({} plugins)".format(path, len(plugin_ids)))


def write_manifest(repository_root, plugin_ids):
    path = os.path.join(repository_root, "habitv-update-manifest.properties")
    lines = build_manifest_lines(repository_root, plugin_ids)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print("Wrote {} ({} lines)".format(path, len(lines)))


def write_directory_index(directory_path):
    entries = []
    for name in sorted(os.listdir(directory_path)):
        full = os.path.join(directory_path, name)
        if os.path.isdir(full):
            entries.append((name + "/", name + "/"))
        else:
            entries.append((name, name))
    html_lines = [
        "<!DOCTYPE html>",
        "<html><head><meta charset=\"UTF-8\"/><title>Index of /</title></head><body>",
        "<h1>Index of /</h1>",
        "<pre><a href=\"../\">Parent Directory</a>",
    ]
    for href, label in entries:
        html_lines.append("<a href=\"{}\">{}</a>".format(href, label))
    html_lines.append("</pre></body></html>")
    with open(os.path.join(directory_path, "index.html"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(html_lines) + "\n")


def write_all_index_html(repository_root):
    for root, dirs, files in os.walk(repository_root):
        write_directory_index(root)
    print("Generated index.html under {}".format(repository_root))


def assert_repository_ready(repository_root):
    if not os.path.isdir(repository_root):
        raise RuntimeError(
            "Static repository path does not exist: {0}. Run Maven deploy first.".format(
                repository_root
            )
        )
    maven_artifacts = os.path.join(repository_root, "com", "dabi", "habitv")
    if not os.path.isdir(maven_artifacts):
        raise RuntimeError(
            "Maven artifacts are missing under {0}. Deploy reactor modules before static-repo-publisher.".format(
                maven_artifacts
            )
        )
    if not os.listdir(maven_artifacts):
        raise RuntimeError("No plugin artifacts found under {0}.".format(maven_artifacts))


def main():
    if len(sys.argv) != 2:
        print("usage: generate_repository_metadata.py <repository-root>", file=sys.stderr)
        sys.exit(1)
    repository_root = os.path.abspath(sys.argv[1])
    assert_repository_ready(repository_root)
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    plugins_pom = os.path.join(repo_root, "plugins", "pom.xml")
    plugin_ids = read_plugin_ids(plugins_pom)
    write_plugins_txt(repository_root, plugin_ids)
    write_manifest(repository_root, plugin_ids)
    write_all_index_html(repository_root)


if __name__ == "__main__":
    main()
