param(
    [Parameter(Mandatory = $false)]
    [Alias("StaticRepoPath")]
    [string]$RepositoryPath,
    [switch]$SkipToolDownloads
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-RepoRoot {
    $scriptDirectory = Split-Path -Parent $PSCommandPath
    return (Resolve-Path (Join-Path $scriptDirectory "..\..")).Path
}

function Resolve-RepositoryPath {
    param([string]$ExplicitPath)

    if (-not [string]::IsNullOrWhiteSpace($ExplicitPath)) {
        $normalized = $ExplicitPath.Trim() -replace '\\', '/'
        if (-not [System.IO.Path]::IsPathRooted($normalized)) {
            throw "RepositoryPath must be an absolute path. Got: $ExplicitPath"
        }
        return $normalized
    }

    $habitvRoot = Get-RepoRoot
    Push-Location $habitvRoot
    try {
        $evaluated = (& mvn help:evaluate "-Dexpression=habitv.static.repo.path" -q "-DforceStdout" | Select-Object -Last 1).Trim()
        if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($evaluated)) {
            throw "Unable to evaluate habitv.static.repo.path."
        }
        return ($evaluated -replace '\\', '/')
    }
    finally {
        Pop-Location
    }
}

function Assert-RepositoryReady {
    param([string]$RepositoryRootOs)

    if (-not (Test-Path -Path $RepositoryRootOs -PathType Container)) {
        throw "Static repository path does not exist: $RepositoryRootOs. Run Maven deploy before the publisher module."
    }

    $mavenArtifacts = Join-Path $RepositoryRootOs "com\dabi\habitv"
    if (-not (Test-Path -Path $mavenArtifacts -PathType Container)) {
        throw "Maven artifacts are missing under $mavenArtifacts. Deploy reactor modules before static-repo-publisher."
    }

    $artifactDirs = Get-ChildItem -Path $mavenArtifacts -Directory -ErrorAction SilentlyContinue
    if ($null -eq $artifactDirs -or $artifactDirs.Count -eq 0) {
        throw "No plugin artifacts found under $mavenArtifacts."
    }
}

function Get-PluginArtifactIds {
    $pluginsPom = Join-Path (Get-RepoRoot) "plugins\pom.xml"
    $content = Get-Content -Path $pluginsPom -Raw
    $ids = [regex]::Matches($content, '<module>([^<]+)</module>') |
        ForEach-Object { $_.Groups[1].Value } |
        Where-Object { $_ -ne 'plugin-tester' }
    return $ids | Sort-Object
}

function Write-PluginsTxt {
    param([string]$RepositoryRoot, [string[]]$PluginIds)

    $path = Join-Path $RepositoryRoot "plugins.txt"
    $lines = @("# Habitv plugin artifact ids (one per line, matches Maven artifactId)") + $PluginIds
    Set-Content -Path $path -Value $lines -Encoding UTF8
    Write-Host "Wrote $path ($($PluginIds.Count) plugins)"
}

function Get-LatestSnapshotJar {
    param([string]$VersionDir)

    $jars = Get-ChildItem -Path $VersionDir -Filter "*.jar" -File |
        Where-Object { $_.Name -notmatch '(-sources|-javadoc)\.jar$' } |
        Sort-Object Name
    if ($jars.Count -eq 0) {
        return $null
    }
    return $jars[$jars.Count - 1]
}

function Build-ManifestLines {
    param([string]$RepositoryRoot, [string[]]$PluginIds)

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by scripts/static-repo/publish-repository-extras.ps1")
    $lines.Add("# type|groupId|artifactId|version|packaging|relativeUrl")

    $groupPath = Join-Path $RepositoryRoot "com\dabi\habitv"
    foreach ($artifactId in $PluginIds) {
        $artifactDir = Join-Path $groupPath $artifactId
        if (-not (Test-Path $artifactDir)) {
            Write-Warning "Skipping manifest plugin $artifactId (not deployed under com/dabi/habitv)"
            continue
        }
        $versionDirs = Get-ChildItem -Path $artifactDir -Directory | Sort-Object Name -Descending
        foreach ($versionDir in $versionDirs) {
            $jar = Get-LatestSnapshotJar -VersionDir $versionDir.FullName
            if ($null -eq $jar) {
                continue
            }
            $relative = "com/dabi/habitv/$artifactId/$($versionDir.Name)/$($jar.Name)"
            $relative = $relative -replace '\\', '/'
            $lines.Add("plugin|com.dabi.habitv|$artifactId|$($versionDir.Name)|jar|$relative")
            break
        }
    }

    $toolsRoot = Join-Path $RepositoryRoot "tools"
    if (Test-Path $toolsRoot) {
        Get-ChildItem -Path $toolsRoot -Directory | ForEach-Object {
            $toolName = $_.Name
            Get-ChildItem -Path $_.FullName -Directory | ForEach-Object {
                $version = $_.Name
                $zip = Get-ChildItem -Path $_.FullName -Filter "*.zip" -File | Select-Object -First 1
                if ($null -ne $zip) {
                    $relative = "tools/$toolName/$version/$($zip.Name)" -replace '\\', '/'
                    $lines.Add("tool|com.dabi.habitv|$toolName|$version|zip|$relative")
                }
            }
        }
    }

    return $lines
}

function Write-Manifest {
    param([string]$RepositoryRoot, [string[]]$PluginIds)

    $path = Join-Path $RepositoryRoot "habitv-update-manifest.properties"
    $lines = Build-ManifestLines -RepositoryRoot $RepositoryRoot -PluginIds $pluginIds
    Set-Content -Path $path -Value $lines -Encoding UTF8
    Write-Host "Wrote $path ($($lines.Count) lines)"
}

function Read-ToolSourceProperties {
    $path = Join-Path (Split-Path -Parent $PSCommandPath) "tool-sources.properties"
    $map = @{}
    foreach ($line in Get-Content -Path $path) {
        $trimmed = $line.Trim()
        if ($trimmed -eq "" -or $trimmed.StartsWith("#")) {
            continue
        }
        if ($trimmed -match '^([^.]+)\.([^=]+)=(.*)$') {
            $currentId = $matches[1]
            $key = $matches[2]
            $value = $matches[3]
            if (-not $map.ContainsKey($currentId)) {
                $map[$currentId] = @{}
            }
            $map[$currentId][$key] = $value
        }
    }
    return $map
}

function Publish-ToolZip {
    param(
        [string]$RepositoryRoot,
        [string]$ArtifactId,
        [hashtable]$Config
    )

    if ($Config.ContainsKey("skip") -and $Config["skip"] -eq "true") {
        Write-Warning "Skipping tool $ArtifactId : $($Config['note'])"
        return
    }
    if ($Config["type"] -eq "skip") {
        Write-Warning "Skipping tool $ArtifactId : $($Config['note'])"
        return
    }

    $version = $Config["version"]
    $destDir = Join-Path $RepositoryRoot "tools\$ArtifactId\$version"
    New-Item -Path $destDir -ItemType Directory -Force | Out-Null
    $zipPath = Join-Path $destDir "$ArtifactId.zip"
    $tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("habitv-tool-" + [guid]::NewGuid().ToString())
    New-Item -Path $tempRoot -ItemType Directory | Out-Null

    try {
        $packagedExe = $Config["packagedExeName"]
        $localExe = Join-Path $tempRoot $packagedExe

        if ($Config["type"] -eq "url") {
            Invoke-WebRequest -Uri $Config["url"] -OutFile $localExe -UseBasicParsing
        }
        elseif ($Config["type"] -eq "zip") {
            $downloadZip = Join-Path $tempRoot "download.zip"
            Invoke-WebRequest -Uri $Config["url"] -OutFile $downloadZip -UseBasicParsing
            Expand-Archive -Path $downloadZip -DestinationPath $tempRoot -Force
            $inner = Join-Path $tempRoot ($Config["innerPath"] -replace '/', '\')
            if (-not (Test-Path $inner)) {
                throw "Expected file not found in archive: $($Config['innerPath'])"
            }
            Copy-Item -Path $inner -Destination $localExe -Force
        }
        else {
            throw "Unsupported tool type $($Config['type']) for $ArtifactId"
        }

        if (Test-Path $zipPath) {
            Remove-Item $zipPath -Force
        }
        Compress-Archive -Path $localExe -DestinationPath $zipPath -Force
        Write-Host "Published tool $ArtifactId $version -> $zipPath"
    }
    finally {
        Remove-Item -Path $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Write-DirectoryIndexHtml {
    param([string]$DirectoryPath)

    $entries = Get-ChildItem -Path $DirectoryPath | Sort-Object { -not $_.PSIsContainer }, Name
    $html = New-Object System.Text.StringBuilder
    [void]$html.AppendLine("<!DOCTYPE html>")
    [void]$html.AppendLine("<html><head><meta charset=""UTF-8""/><title>Index of /</title></head><body>")
    [void]$html.AppendLine("<h1>Index of /</h1>")
    [void]$html.AppendLine("<pre><a href=""../"">Parent Directory</a>")
    foreach ($entry in $entries) {
        $name = $entry.Name
        if ($entry.PSIsContainer) {
            $name = "$name/"
        }
        [void]$html.AppendLine("<a href=""$name"">$name</a>")
    }
    [void]$html.AppendLine("</pre></body></html>")
    Set-Content -Path (Join-Path $DirectoryPath "index.html") -Value $html.ToString() -Encoding UTF8
}

function Write-AllIndexHtml {
    param([string]$RepositoryRoot)

    Get-ChildItem -Path $RepositoryRoot -Recurse -Directory | ForEach-Object {
        Write-DirectoryIndexHtml -DirectoryPath $_.FullName
    }
    Write-DirectoryIndexHtml -DirectoryPath $RepositoryRoot
    Write-Host "Generated index.html files under $RepositoryRoot"
}

$repositoryRoot = Resolve-RepositoryPath -ExplicitPath $RepositoryPath
$repositoryRootOs = ($repositoryRoot -replace '/', [System.IO.Path]::DirectorySeparatorChar)

Assert-RepositoryReady -RepositoryRootOs $repositoryRootOs

$pluginIds = Get-PluginArtifactIds

if (-not $SkipToolDownloads) {
    $toolSources = Read-ToolSourceProperties
    foreach ($artifactId in $toolSources.Keys | Sort-Object) {
        try {
            Publish-ToolZip -RepositoryRoot $repositoryRootOs -ArtifactId $artifactId -Config $toolSources[$artifactId]
        }
        catch {
            Write-Warning "Failed to publish tool ${artifactId}: $($_.Exception.Message)"
        }
    }
}
else {
    Write-Host "Skipping tool downloads (-SkipToolDownloads)."
}

Write-PluginsTxt -RepositoryRoot $repositoryRootOs -PluginIds $pluginIds
Write-Manifest -RepositoryRoot $repositoryRootOs -PluginIds $pluginIds
Write-AllIndexHtml -RepositoryRoot $repositoryRootOs

Write-Host "Done. Repository root: $repositoryRoot"
