# Reject known tool-generated PR description blocks (public git text policy).
# Usage: pwsh -File scripts/validate-pr-public-body.ps1 [-Body $text] [-BodyFile path]
# Exit 0 when clean, 1 when a forbidden marker is present.

param(
    [string] $Body = "",
    [string] $BodyFile = ""
)

$ErrorActionPreference = "Stop"

if ($BodyFile) {
    $Body = Get-Content -Raw $BodyFile
} elseif (-not $Body -and $env:PR_BODY) {
    $Body = $env:PR_BODY
}

if ([string]::IsNullOrEmpty($Body)) {
    Write-Host "pr-public-body: OK (empty)"
    exit 0
}

$markers = @(
    "Summary by Sourcery",
    "Generated by sourcery",
    "auto-generated description by cubic",
    "Review in cubic",
    "Written for commit",
    "Summary will update on new commits",
    "CURSOR_AUTOMATION_ID"
)

foreach ($marker in $markers) {
    if ($Body.Contains($marker)) {
        Write-Host "pr-public-body: forbidden generated block detected: $marker"
        exit 1
    }
}

Write-Host "pr-public-body: OK"
exit 0
