#!/usr/bin/env bash
# Reject known tool-generated PR description blocks (public git text policy).
# Usage:
#   scripts/validate-pr-public-body.sh              # read body from stdin
#   scripts/validate-pr-public-body.sh /path/file
#   PR_BODY='...' scripts/validate-pr-public-body.sh
# Exit 0 when clean, 1 when a forbidden marker is present.

set -euo pipefail

body="${PR_BODY:-}"
if [[ $# -gt 0 ]]; then
  body="$(cat "$1")"
elif [[ -z "$body" ]]; then
  body="$(cat)"
fi

if [[ -z "$body" ]]; then
  echo "pr-public-body: OK (empty)"
  exit 0
fi

markers=(
  'Summary by Sourcery'
  'Generated by sourcery'
  'auto-generated description by cubic'
  'Review in cubic'
  'Written for commit'
  'Summary will update on new commits'
  'CURSOR_AUTOMATION_ID'
)

for marker in "${markers[@]}"; do
  if printf '%s' "$body" | grep -qF "$marker"; then
    echo "pr-public-body: forbidden generated block detected: $marker"
    exit 1
  fi
done

echo "pr-public-body: OK"
exit 0
